version: "3.8"
services:
  db:
    container_name: "post"
    image: "postgres"
    volumes:
      - mydb:/var/lib/postgresql/data
    env_file:
      - config/Back.evn
    restart: always
    ports:
      - "5432:5432"
  backend:
    build: ./elflowServer
    ports:
      - "3007:3007"
    env_file:
      - config/Back.evn

    depends_on:
      - db
  frontend:
    build: ./elflowReact
    ports:
      - "80:80"
    env_file:
      - config/Front.evn

volumes:
  mydb:
    driver: local