version: "3.8"
services:
  db:
    container_name: "post"
    image: "postgres"
    volumes:
      - mydb:/var/lib/postgresql/data
    env_file:
      - config/Back.env
    restart: always
    ports:
      - "5430:5430"
  backend:
    build:
      context: ./elflowServer
      dockerfile: Dockerfile.prod
    ports:
      - "3007:3007"
    env_file:
      - config/Back.env
    restart: always
    depends_on:
      - db
  frontend:
    build:
      context: ./elflowReact
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - config/Front.env
    restart: always
volumes:
  mydb:
    driver: local