version: "3.8"
services:
  db:
    container_name: "post"
    image: "postgres"
    volumes:
      - mydb:/var/lib/postgresql/data
    env_file:
      - config/Back.evn
    restart: always
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "3007:3007"
    env_file:
      - config/Back.evn
    restart: always
    depends_on:
      - db
  frontend:
    build: ./elflowReact
    ports:
      - "80:3000"
    env_file:
      - config/Front.evn
    restart: always
volumes:
  mydb:
    driver: local